on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  build:
    permissions:
      packages: write
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image
        run: |
          REPO=$(echo -n ghcr.io/${GITHUB_REPOSITORY} | tr [:upper:] [:lower:])
          docker build -t $REPO:$GITHUB_SHA .
          docker tag $REPO:$GITHUB_SHA $REPO:latest
          docker push $REPO:$GITHUB_SHA
          docker push $REPO:latest